### ISSUE TITLE
Carbon Fields version

### ISSUE THREAD

**Issue by Mick00** [iamntz/carbon-rest-multiselect#1]
Hi, I am currently using Carbon-Fields and I need something like this, but is it compatible with Carbon-Fields 3.0? Also, when I try to add it to composer it says that there are no stable package found. So is it ready for production?

**Comment by iamntz** [comment]
Hey @Mick00 Currently the plugin works only with Carbon 2.x. There are big changes that it will be update in the following weeks to 3.x.

In order to work with Composer you _might_ need to adjust the [minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) option.

**Comment by Mick00** [comment]
Ok, thanks

**Comment by iamntz** [comment]
Hey @Mick00 I've managed to add V3 compatibility. Let me know if you find any issues with these new changes.

**Comment by Mick00** [comment]
Ok, kind of rolled without it, but I might try it anyway.
